### ISSUE TITLE
Example config is 404

### ISSUE THREAD

**Issue by tyler36** [mmunz/ddev-backstopjs#1]
I was following through the readme when I hit the following

> Hint: have a look at the config the author uses: [https://github.com/mmunz/backstopjs-config](https://github.com/mmunz/ddev-backstopjs/blob/main/backstopjs-config)

When I tried to click through, Github threw a `404` error.

**Comment by mmunz** [comment]
Thanks @tyler36, i fixed the link.

**Comment by tyler36** [comment]
Wow, that was quick! 

Confirmed. Link now working for me. Thank you!
